version: 2

sources:
  - name: erp_adventureworks
    description: Sistema de vendas da empresa Adventure Works.
    database: fea24_9
    schema: raw_adventure_works
    tables:
      - name: salesorderheader
        description: Contém informações gerais sobre cada pedido.
        columns:
          - name: salesorderid
            data_tests:
              - unique
              - not_null
      - name: salesorderdetail
        description: Contém detalhes de cada item dentro de um pedido.
        columns:
          - name: idsalesorderdetailid
            data_tests:
              - unique
              - not_null          