version: 2

sources:
  - name: erp_adventureworks
    description: Sistema de vendas da empresa Adventure Works.
    database: fea24_9
    schema: raw_adventure_works
    tables:
      - name: salesorderheader
        description: Contém informações gerais sobre cada pedido.
        columns:
          - name: salesorderid
            data_tests:
              - unique
              - not_null
      - name: salesorderdetail
        description: Contém detalhes de cada item dentro de um pedido.
        columns:
          - name: salesorderdetailid
            data_tests:
              - unique
              - not_null          

      - name: product
        description: Contém informações detalhadas sobre cada produto.
        columns:
          - name: productid
            data_tests:
              - unique
              - not_null

      - name: productsubcategory
        description: Contém o agrupamento dos produtos por subcategorias.
        columns:
          - name: productsubcategoryid
            data_tests:
              - unique
              - not_null

      - name: productcategory
        description: Contém o agrupamento dos produtos por categorias mais amplas.
        columns:
          - name: productcategoryid
            data_tests:
              - unique
              - not_null

      - name: salesorderheadersalesreason
        description: Contém o relacionamento entre pedidos com e os motivos da venda.
        columns:
          - name: salesorderid
            data_tests:
              - not_null 
              
      - name: salesreason
        description: Contém os motivos das vendas.
        columns:
          - name: salesreasonid
            data_tests:
              - unique
              - not_null
      - name: creditcard
        description: Contém informações sobre os cartões de crédito dos clientes, caso aplicável.
        columns:
          - name: creditcardid
            data_tests:
              - unique
              - not_null

      - name: address
        description: Contém endereços de clientes, lojas e outros locais.
        columns:
          - name: addressid
            data_tests:
              - unique
              - not_null             

      - name: stateprovince
        description: Contém informações sobre os estados e províncias.
        columns:
          - name: stateprovinceid
            data_tests:
              - unique
              - not_null
              
      - name: countryregion
        description: Contém informações sobre os países.
        columns:
          - name: countryregioncode
            data_tests:
              - unique
              - not_null
              
      - name: customer
        description: Contém informações sobre os clientes.
        columns:
          - name: customerid
            data_tests:
              - unique
              - not_null
              
      - name: store
        description: Contém informações sobre as lojas físicas da empresa
        columns:
          - name: businessentityid
            data_tests:
              - unique
              - not_null 
              
      - name: person
        description: Informações sobre pessoas físicas.
        columns:
          - name: businessentityid
            data_tests:
              - unique
              - not_null              